version: "3.8"
services:
    nginx:
        build:
            context: docker/nginx
        ports:
            - "8888:80"
        volumes:
            - ./:/app
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            - ./:/app

